name: Pull request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  check-changed-files-count:
    outputs:
      count: ${{ steps.changed-files.outputs.all_modified_files_count }}
      changed_files: ${{ steps.changed-files.outputs.all_modified_files }}
    permissions:
      actions: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Check commit message convention
        run: |
          yarn add @commitlint/cli @commitlint/config-conventional -D
          yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          json: true
          write_output_files: true
          files: 'src/**/*.{js,ts,jsx,tsx,json,html,css,scss,sass,graphql}'
          files_ignore: 'src/**/*.{jpg,jpeg,png,pneg,svg,webp,mp4,webm,ogg,mp3,wav,flac,aac,wma,flv,avi,mov,wmv,mpg,mkv,flv,3gp,3g2,ts,mts,m2ts,vob,asf,rm,rmvb,dat,iso,zip,rar,7z,tar,gz,tgz,arj,ace,deb,apk,exe,msi,dmg,bin,iso,torrent}'

      - name: Verify the contents of the .github/outputs/modified_files.json file
        run: |
          cat .github/outputs/modified_files.json

      - name: Check changed files
        run: |
          if [ ${{ steps.changed-files.outputs.all_modified_files_count }} -gt 15 ]; then
            echo "Too many files changed. One PR should only change <= 15 files."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-and-test:
    runs-on: ubuntu-latest
    needs: check-changed-files-count
    if: needs.check-changed-files-count.outputs.count != '0'
    steps:
      - name: Add quotes
        id: add-quotes
        run: |
          echo changed_files_with_quotes="'${{ needs.check-changed-files-count.outputs.changed_files }}'" | sed "s/ /' '/g" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Lint check
        run: |
          yarn eslint ${{ steps.add-quotes.outputs.changed_files_with_quotes }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Jest tests and check branches coverage
        run: |
          sudo apt-get update
          sudo apt-get install jq

          yarn test:cov-json-summary
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Unit tests failed with exit code $exit_code. Stopping the workflow."
            exit $exit_code
          fi

          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.branches.pct')
          MIN_THRESHOLD=80

          echo "Branches coverage is $COVERAGE% ✅"

          if [ "$COVERAGE" -lt "$MIN_THRESHOLD" ]; then
            echo "Branches coverage $COVERAGE% is below the threshold $MIN_THRESHOLD%. Aborting the workflow."
            exit 1
          fi
        env:
          CI: true
        continue-on-error: true
